# Generated by Django 2.1.3 on 2018-11-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
    ]
