# Generated by Django 2.1.3 on 2018-11-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_school', '0002_auto_20181110_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='id_class',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
