# Generated by Django 2.1.3 on 2018-11-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_school', '0003_schedule_id_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='id_lesson_number',
            new_name='lesson_number',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_school.Class_Name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_school.Day'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_school.Subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_school.Teacher'),
        ),
    ]
